# Generated by Django 5.2 on 2025-04-18 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок страницы', max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Порядок в меню')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'db_table': 'pages',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('news', 'News'), ('events', 'Events'), ('media', 'Media'), ('form', 'Form'), ('contacts', 'Contacts')], help_text='Тип контента', max_length=50)),
                ('title', models.CharField(help_text='Заголовок', max_length=255)),
                ('body', models.JSONField(help_text='Содержание', null=True)),
                ('media_url', models.URLField(blank=True, help_text='Медиа', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], help_text='Статус', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Создано')),
                ('author', models.ForeignKey(help_text='Автор', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контент',
                'db_table': 'contents',
            },
        ),
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='pending', help_text='Статус', max_length=20)),
                ('comment', models.TextField(blank=True, help_text='Комментарий')),
                ('moderated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(help_text='Контент', on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='core.content')),
                ('moderated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_by', to='users.profile')),
            ],
            options={
                'verbose_name': 'Модерация',
                'verbose_name_plural': 'Модерации',
                'db_table': 'moderations',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('slider', 'Slider'), ('text', 'Text'), ('gallery', 'Gallery'), ('media', 'Media'), ('news', 'News'), ('events', 'Events'), ('contacts', 'Contacts'), ('map', 'Map'), ('form', 'Form')], max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Порядок')),
                ('settings', models.JSONField(help_text='Настройки')),
                ('page', models.ForeignKey(help_text='Страница', on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.page')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
                'db_table': 'blocks',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название сайта', max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Создан:')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Изменен:')),
                ('created_by', models.ForeignKey(help_text='Создано пользователем:', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='users.profile')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты',
                'db_table': 'sites',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Учреждение', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.site'),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_colors', models.JSONField(help_text='Цвета темы')),
                ('fonts', models.JSONField(help_text='Шрифты')),
                ('logo', models.ImageField(blank=True, help_text='Лого', null=True, upload_to='site_settings/logo')),
                ('spacing', models.JSONField(help_text='Интервал')),
                ('site', models.OneToOneField(help_text='Сайт', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.site')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайтов',
                'db_table': 'site_settings',
            },
        ),
    ]
